### PR TITLE
Creating Models

### PR DESCRIPTION
**Pull request by sncandiani**
git fetch --all
git checkout (sc-trainingprogram1)
Summary of this pull request: Created models as a group.

List of specifics:
- python manage.py makemigrations hrapp to initialize 
- python manage.py migrate 
- Create a connection.py that imports your db and use in your employeelist

### CODE REVIEW

**Comment by kwohl** [comment]
looks great!

**Review by MatthewScott32 — APPROVED** [review]
Looks Good

**Review by kwohl — APPROVED** [review]

**Review by HalcyonVagabond — APPROVED** [review]
Wow, great job! Keep it up! Proud of you!

**Review by mKroogz — APPROVED** [review]
Looks Great!!!

**Pull request merged**
